# Generated by Django 5.1.4 on 2026-01-06 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da atração', max_length=200, verbose_name='Nome')),
                ('type', models.CharField(choices=[('monument', 'Monumento'), ('museum', 'Museu'), ('park', 'Parque'), ('restaurant', 'Restaurante'), ('viewpoint', 'Mirante'), ('beach', 'Praia'), ('church', 'Igreja/Templo'), ('shopping', 'Compras'), ('nightlife', 'Vida Noturna'), ('other', 'Outro')], default='other', help_text='Categoria da atração', max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada da atração', verbose_name='Descrição')),
                ('fun_fact', models.TextField(blank=True, help_text='Uma curiosidade ou fato interessante sobre a atração', verbose_name='Curiosidade')),
            ],
            options={
                'verbose_name': 'Atração',
                'verbose_name_plural': 'Atrações',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttractionTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título resumido da dica', max_length=200, verbose_name='Título')),
                ('category', models.CharField(choices=[('todo', 'O que fazer'), ('toeat', 'O que comer'), ('other', 'Outro')], default='other', help_text='Categoria da dica', max_length=20, verbose_name='Categoria')),
                ('attraction', models.ForeignKey(help_text='Atração relacionada à dica', on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='itinerary.attraction', verbose_name='Atração')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da cidade', max_length=200, verbose_name='Nome')),
                ('country', models.CharField(help_text='País onde a cidade está localizada', max_length=100, verbose_name='País')),
                ('description', models.TextField(blank=True, help_text='Descrição geral da cidade', verbose_name='Descrição')),
                ('arrival_date', models.DateTimeField(verbose_name='Data da chegada')),
                ('departure_date', models.DateTimeField(verbose_name='Data da partida')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['country', 'name'],
                'indexes': [models.Index(fields=['country', 'name'], name='itinerary_c_country_65e1e0_idx')],
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.AddField(
            model_name='attraction',
            name='city',
            field=models.ForeignKey(help_text='Cidade onde a atração está localizada', on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='itinerary.city', verbose_name='Cidade'),
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['city', 'type'], name='itinerary_a_city_id_a7d886_idx'),
        ),
    ]
