# Generated by Django 5.1.4 on 2026-01-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attractiontip',
            options={'ordering': ['attraction', 'category', 'title'], 'verbose_name': 'Dica da Atração', 'verbose_name_plural': 'Dicas da Atração'},
        ),
        migrations.AlterUniqueTogether(
            name='attractiontip',
            unique_together={('title', 'attraction')},
        ),
        migrations.AddIndex(
            model_name='attractiontip',
            index=models.Index(fields=['attraction'], name='itinerary_a_attract_d93325_idx'),
        ),
    ]
