# Generated by Django 5.1.4 on 2026-01-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_alter_attractiontip_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='priority_order',
            field=models.IntegerField(blank=True, help_text='Ordem de prioridade da visita (1 = mais prioritária)', null=True, verbose_name='Ordem de prioridade'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='suggested_duration',
            field=models.IntegerField(blank=True, help_text='Tempo sugerido de permanência na atração em minutos', null=True, verbose_name='Tempo sugerido (minutos)'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='visited',
            field=models.BooleanField(default=False, help_text='Indica se a atração já foi visitada', verbose_name='Visitado'),
        ),
    ]
