# Generated by Django 5.1.4 on 2026-01-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0003_attraction_priority_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto representativa da atração', null=True, upload_to='attractions/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='city',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto representativa da cidade', null=True, upload_to='cities/', verbose_name='Foto'),
        ),
    ]
